"""initial

Revision ID: 2e71772da300
Revises: 
Create Date: 2026-03-25 22:33:06.831674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e71772da300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('password_reset_token_hash', sa.String(length=128), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('display_label', sa.String(length=120), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('extra_settings_json', sa.JSON(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_provider_configs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_ai_provider_user_kind', ['user_id', 'kind'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_secret_name')
    )
    with op.batch_alter_table('user_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_secrets_user_id'), ['user_id'], unique=False)

    op.create_table('youtube_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'google_channel_id', name='uq_user_yt_channel')
    )
    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_channels_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_yt_channels_user_status', ['user_id', 'status'], unique=False)

    op.create_table('automation_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('youtube_channel_id', sa.Integer(), nullable=True),
    sa.Column('llm_provider_id', sa.Integer(), nullable=True),
    sa.Column('video_provider_id', sa.Integer(), nullable=True),
    sa.Column('voice_provider_id', sa.Integer(), nullable=True),
    sa.Column('videos_per_day', sa.Float(), nullable=False),
    sa.Column('duration_min_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_max_seconds', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('tone', sa.String(length=64), nullable=False),
    sa.Column('cta_style', sa.String(length=64), nullable=False),
    sa.Column('master_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_format', sa.String(length=16), nullable=False),
    sa.Column('publish_mode', sa.String(length=16), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['ai_provider_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_provider_id'], ['ai_provider_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_provider_id'], ['ai_provider_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['youtube_channel_id'], ['youtube_channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('content_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_profile_id', sa.Integer(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_profile_id'], ['automation_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_ideas_automation_profile_id'), ['automation_profile_id'], unique=False)

    op.create_table('content_usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('automation_profile_id', sa.Integer(), nullable=True),
    sa.Column('usage_type', sa.String(length=24), nullable=False),
    sa.Column('normalized_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('sample_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_profile_id'], ['automation_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_usage_records_automation_profile_id'), ['automation_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_usage_records_normalized_fingerprint'), ['normalized_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_usage_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_usage_user_type_fp', ['user_id', 'usage_type', 'normalized_fingerprint'], unique=False)

    op.create_table('title_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_profile_id', sa.Integer(), nullable=False),
    sa.Column('content_idea_id', sa.Integer(), nullable=True),
    sa.Column('title_text', sa.String(length=500), nullable=False),
    sa.Column('hook_category', sa.String(length=32), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('repetition_penalty', sa.Float(), nullable=False),
    sa.Column('variants_json', sa.JSON(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('semantic_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_profile_id'], ['automation_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_idea_id'], ['content_ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['title_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('title_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_candidates_automation_profile_id'), ['automation_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_title_candidates_semantic_fingerprint'), ['semantic_fingerprint'], unique=False)

    op.create_table('script_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_candidate_id', sa.Integer(), nullable=False),
    sa.Column('hook_opening', sa.Text(), nullable=True),
    sa.Column('promise', sa.Text(), nullable=True),
    sa.Column('beats_json', sa.JSON(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('micro_retentions_json', sa.JSON(), nullable=True),
    sa.Column('cta_organic', sa.Text(), nullable=True),
    sa.Column('closing', sa.Text(), nullable=True),
    sa.Column('voiceover_final', sa.Text(), nullable=True),
    sa.Column('subtitles_text', sa.Text(), nullable=True),
    sa.Column('description_seo', sa.Text(), nullable=True),
    sa.Column('hashtags_json', sa.JSON(), nullable=True),
    sa.Column('thumbnail_prompt', sa.Text(), nullable=True),
    sa.Column('scene_prompts_json', sa.JSON(), nullable=True),
    sa.Column('format_kind', sa.String(length=32), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('publish_readiness_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['title_candidate_id'], ['title_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('script_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_drafts_title_candidate_id'), ['title_candidate_id'], unique=False)

    op.create_table('production_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_draft_id', sa.Integer(), nullable=False),
    sa.Column('scenes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_draft_id'], ['script_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_plans_script_draft_id'), ['script_draft_id'], unique=False)

    op.create_table('render_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_draft_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('qa_score', sa.Float(), nullable=True),
    sa.Column('qa_details_json', sa.JSON(), nullable=True),
    sa.Column('log_excerpt', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_draft_id'], ['script_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_jobs_script_draft_id'), ['script_draft_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_plan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_production_plan_id'), ['production_plan_id'], unique=False)

    op.create_table('publication_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('render_job_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_status', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['render_job_id'], ['render_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_jobs_render_job_id'), ['render_job_id'], unique=False)

    op.create_table('published_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.Integer(), nullable=False),
    sa.Column('publication_job_id', sa.Integer(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publication_job_id'], ['publication_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['youtube_channel_id'], ['youtube_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_job_id')
    )
    with op.batch_alter_table('published_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_videos_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_videos_youtube_channel_id'), ['youtube_channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_videos_youtube_video_id'), ['youtube_video_id'], unique=False)

    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_video_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['published_video_id'], ['published_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_published_video_id'), ['published_video_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_profile_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('stages_json', sa.JSON(), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('content_idea_id', sa.Integer(), nullable=True),
    sa.Column('title_candidate_id', sa.Integer(), nullable=True),
    sa.Column('script_draft_id', sa.Integer(), nullable=True),
    sa.Column('production_plan_id', sa.Integer(), nullable=True),
    sa.Column('render_job_id', sa.Integer(), nullable=True),
    sa.Column('publication_job_id', sa.Integer(), nullable=True),
    sa.Column('published_video_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_profile_id'], ['automation_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_idea_id'], ['content_ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publication_job_id'], ['publication_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_video_id'], ['published_videos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_job_id'], ['render_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_draft_id'], ['script_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['title_candidate_id'], ['title_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_automation_profile_id'), ['automation_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_automation_profile_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_published_video_id'))

    op.drop_table('analytics_snapshots')
    with op.batch_alter_table('published_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_videos_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_published_videos_youtube_channel_id'))
        batch_op.drop_index(batch_op.f('ix_published_videos_user_id'))

    op.drop_table('published_videos')
    with op.batch_alter_table('publication_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_jobs_render_job_id'))

    op.drop_table('publication_jobs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_production_plan_id'))

    op.drop_table('assets')
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_render_jobs_script_draft_id'))

    op.drop_table('render_jobs')
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_plans_script_draft_id'))

    op.drop_table('production_plans')
    with op.batch_alter_table('script_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_drafts_title_candidate_id'))

    op.drop_table('script_drafts')
    with op.batch_alter_table('title_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_candidates_semantic_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_title_candidates_automation_profile_id'))

    op.drop_table('title_candidates')
    with op.batch_alter_table('content_usage_records', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_user_type_fp')
        batch_op.drop_index(batch_op.f('ix_content_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_content_usage_records_normalized_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_content_usage_records_automation_profile_id'))

    op.drop_table('content_usage_records')
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_ideas_automation_profile_id'))

    op.drop_table('content_ideas')
    with op.batch_alter_table('automation_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_profiles_user_id'))

    op.drop_table('automation_profiles')
    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.drop_index('ix_yt_channels_user_status')
        batch_op.drop_index(batch_op.f('ix_youtube_channels_user_id'))

    op.drop_table('youtube_channels')
    with op.batch_alter_table('user_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_secrets_user_id'))

    op.drop_table('user_secrets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_provider_user_kind')
        batch_op.drop_index(batch_op.f('ix_ai_provider_configs_user_id'))

    op.drop_table('ai_provider_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
